In [33]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC


from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris (1).csv


In [34]:
import io
iris= pd.read_csv('Iris.csv')
print(iris.shape)
print(iris.columns)


(150, 6)
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')


In [35]:
x=iris.drop(['Species'],axis=1)
y=iris['Species']

In [36]:
from sklearn.model_selection import train_test_split


# Split the dataset into training and testing sets (70% for training and 30% for testing)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)


####KNN CLASSIFIER


In [37]:
# Create a k-NN classifier with k=3 (you can choose a different value for k)
knn = KNeighborsClassifier(n_neighbors=3)

# Train the k-NN model on the training data
knn.fit(x_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [40]:
# Make predictions on the test set
from sklearn.metrics import accuracy_score
y_pred = knn.predict(x_test)

# Calculate the accuracy of the model
print(accuracy_score(y_test, y_pred))



1.0


DECISION  TREE CLASSIFIER

In [41]:
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(x_train, y_train)


y_pred = dt_classifier.predict(x_test)
accuracy_score(y_test, y_pred)

1.0

LOGISTIC REGRESSION

In [43]:
logistic_regression = LogisticRegression(random_state=42)
logistic_regression.fit(x_train, y_train)


y_pred = logistic_regression.predict(x_test)
print(accuracy_score(y_test, y_pred))


1.0


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


SVM CLASSIFIER

In [45]:
svm_classifier = SVC(random_state=42)
svm_classifier.fit(x_train, y_train)


y_pred = svm_classifier.predict(x_test)
print(accuracy_score(y_test, y_pred))

1.0


NAIVE BAYES CLASSIFIER

In [46]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(x_train, y_train)


y_pred = nb_classifier.predict(x_test)
print(accuracy_score(y_test, y_pred))

1.0


CONFUSION MATRIX


In [49]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
